[package]
name = "openkey-core-credentials"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Resident and discoverable credentials management for OpenKey FIDO2"

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
zeroize = { workspace = true }
