[package]
name = "storage-example"
version = "0.1.1"
edition = "2021"
description = "Minimal example of credential storage and retrieval"
license = "MIT"

[dependencies]
authenticator = { package = "openkey-device", path = "../../crates/openkey-device", version = "0.1.1" }
board-generic = { package = "openkey-hal", path = "../../crates/openkey-hal", version = "0.1.1" }
crypto = { package = "openkey-crypto", path = "../../crates/openkey-crypto", version = "0.1.1" }
ctap2 = { package = "openkey-core", path = "../../crates/openkey-core", version = "0.1.1" }
log = "0.4"
env_logger = "0.11"

[[bin]]
name = "storage-example"
path = "src/main.rs"
